/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CongratsImport } from './routes/congrats'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const CongratsRoute = CongratsImport.update({
  id: '/congrats',
  path: '/congrats',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/congrats': {
      id: '/congrats'
      path: '/congrats'
      fullPath: '/congrats'
      preLoaderRoute: typeof CongratsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/congrats': typeof CongratsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/congrats': typeof CongratsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/congrats': typeof CongratsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/congrats'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/congrats'
  id: '__root__' | '/' | '/congrats'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CongratsRoute: typeof CongratsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CongratsRoute: CongratsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/congrats"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/congrats": {
      "filePath": "congrats.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
